name: deploy-ri

on:
  push:
    branches:
      - react-iframe

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: yarn deploy:ri

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.HOBOX_EXAMPLES_TOKEN }}
        publish_dir: ./build